### ISSUE TITLE
setTimeout is called after reject

### ISSUE THREAD

**Issue by iceberk** [TheBrainFamily/wait-for-expect#10]
Hello,

I am running mocha tests in 'watch' mode and noticed that expectations are still being checked after timeout and test failure, because there is no return after reject(error) in waitForExpect and setTimout is called again and again.
Is it intended behaviour?

**Comment by kentcdodds** [comment]
Ah, that's interesting. I think there should be a return on or after this line:

https://github.com/TheBrainFamily/wait-for-expect/blob/e910af64c054eda3bd4cf5931c3e296d419504ff/src/index.ts#L22

What do you think @lgandecki?

**Comment by lgandecki** [comment]
Good catch!

@iceberk do you want to become a contributor to this tiny package? ;-) Otherwise I will make the change today or tomorrow.

**Comment by iceberk** [comment]
Sure, will try to send a request today.

**Comment by lgandecki** [comment]
fixed in 1.0.1 , thanks @iceberk and thanks @kentcdodds !
