### ISSUE TITLE
Never rejects if Date.now is mocked in the test

### ISSUE THREAD

**Issue by valignatev** [TheBrainFamily/wait-for-expect#12]
Hi there, thanks for a nice and convenient package!

This is mostly the same case as #4, but `Date.now` is mocked instead of `setTimeout`. And if the `Date.now` is mocked, this condition: https://github.com/TheBrainFamily/wait-for-expect/blob/master/src/index.ts#L21 will be either always true, or always false. So tests with mocked Date.now will either fail without retrying, or fail with temeout error.

The solution for this is always to use the real Date.now the same way we're doing with setTimeout. I'll provide a PR for this where we can continue the discussion.

**Comment by valignatev** [comment]
Bonus: example of such mock in the real world: https://github.com/facebook/jest/blob/6d3da9be06350bfa7414b609807ebd0cbdf0c416/examples/snapshot/__tests__/clock.react.test.js#L11

**Comment by lgandecki** [comment]
Merged and released, thank you so much :-)

**Comment by chetmurphy** [comment]
I am using typescript with react-hooks-testing-library that uses this library. To get tests to run, I had to mock Date in my tests

```ts
declare global {
  interface Window { Date: any; }
}
window.Date = Date;
```
And comment out the code in wait-for-expect starting at line 16: 
```ts
var _ref = typeof window !== "undefined" ? window : global,
   setTimeout = _ref.setTimeout,
   now = _ref.Date.now;
```
Is this a bug?

**Comment by lgandecki** [comment]
Could you please make a small reproduction that shows the problem?

**Comment by chetmurphy** [comment]
Repro at https://github.com/chetmurphy/wait-for-expect-test

After installing with yarn run yarn test – will fail

  ● Test suite failed to run

    TypeError: Cannot read property 'now' of undefined

      at Object.<anonymous> (node_modules/wait-for-expect/lib/index.js:16:21)
      at Object.<anonymous> (node_modules/dom-testing-library/dist/wait.js:10:45)
      at Object.<anonymous> (node_modules/dom-testing-library/dist/index.js:83:13)

Test Suites: 1 failed, 1 total

Comment out wait for expect section at wait-for-expect/lib/index.js:16

Rerun yarn test - should succeed.

--Chet

________________________________
