### ISSUE TITLE
TypeError: Cannot read property 'now' of undefined in 1.1.0

### ISSUE THREAD

**Issue by maikthomas** [TheBrainFamily/wait-for-expect#15]
I have tests failing with this error after updating to version 1.1.0.
We are mocking the date with sinon.
This happened just importing the module in a helper file, not actually using any methods of wait-for-expect.
The error comes from the `index.js`, I imagine it's the destructuring here: https://github.com/TheBrainFamily/wait-for-expect/blob/master/src/index.ts#L13
```
  Uncaught exception in <test path>

  /node_modules/wait-for-expect/lib/index.js:16

  TypeError: Cannot read property 'now' of undefined

  Object.<anonymous> (
node_modules/wait-for-expect/lib/index.js:16:21)
  Module._compile (
/node_modules/pirates/lib/index.js:83:24)
  Object.newLoader [as .js] (
/node_modules/pirates/lib/index.js:88:7)

```

**Comment by lgandecki** [comment]
Thanks for letting us know.

would you be able to make a simple reproduction?
I'm curious to see what do you have as your window or global 
You say you mock the date.. but that shouldn't make it undefined?

**Comment by maikthomas** [comment]
Sorry it looks like this is an issue with JSDom, will open an issue with them 👍

**Comment by maikthomas** [comment]
Wow quick response @lgandecki ! 😅 
Here's the repro for jsdom: https://repl.it/repls/WellinformedSmartFiles

**Comment by lgandecki** [comment]
@kentcdodds usually beats me to it - so I have to be on watch ;-)

**Comment by kentcdodds** [comment]
You were preeeety quick that time!

**Comment by eric-burel** [comment]
Hi, lost googler here, did you eventually open an issue on JSdom ?
For the record I get this issue trying to run `react-testing-library` server-side.I can't figure out a solution right now, in the JSDom repo I found [this issue](https://github.com/jsdom/jsdom/issues/2446) about `window.Date`, but it does not seem to make sense in a server-side context.

**Comment by lgandecki** [comment]
@eric-burel Would you be able to make a simple reproduction?

**Comment by eric-burel** [comment]
Will try to do that asap.
I guess this issue happens when we mess up `window`, eg by mocking it in a test. I think it will then fetch `Date` in an ill-defined `window`, and fails to find it. 
Could we improve [this line](https://github.com/TheBrainFamily/wait-for-expect/blob/master/src/index.ts#L13) to be more robust to this, given that we can easily mess up window in a server-side test?

Like in 2 lines:
```
const { now } = window && window.Date  || global && global.Date || {}
if (!now) throw new Error("Please define window.Date.now or global.Date.now. You may have altered those value during your test setup/mock.")
// same for set timeout
```
I can PR in a few days if you think it would be relevant. It would at least help debug.
