### ISSUE TITLE
Suggestion for docs - nested waitForExpect

### ISSUE THREAD

**Issue by jackgeek** [TheBrainFamily/wait-for-expect#19]
First off, great library, thank you for your hard work!

In the docs you show that you can use an await within a waitForExpect callback.  I was thinking that perhaps a good example might be to show a nested waitForExpect?

This is something I have found in my tests:

```
await waitForExpect(async () => {
   expect(animatedThing.isVisible).toBe(true);
   animatedThing.toggle();
   await waitForExpect(async () => {
      expect(animatedThing.isVisible).toBe(false)
   });
});
```

**Comment by lgandecki** [comment]
Hello, thanks! :-)

what would be advantage of doing that comparing to just 
```javascript
await waitForExpect(async () => {
   expect(animatedThing.isVisible).toBe(true);
});
animatedThing.toggle();
await waitForExpect(async () => {
      expect(animatedThing.isVisible).toBe(false)
});
```
?

**Comment by jackgeek** [comment]
Well you got me.  I hadn't thought of that usage!

Its effectively the same.

Never mind my suggestion is not a good idea.

Thanks for your consideration and teaching me the error of my ways.

Kind regards,
Jack

**Comment by lgandecki** [comment]
No problem! happy to help
