### ISSUE TITLE
Library doesn't encount for extra needed time inside expectation callback

### ISSUE THREAD

**Issue by Hianz** [TheBrainFamily/wait-for-expect#27]
If there are expectations to wait for that need extra time for example with enzymes `update` function jest will throw an error especially in combination wraped with act, since it exceeds the default timeout of 5000ms defined by jest with the following error message:

`Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout`

**Comment by lgandecki** [comment]
Did you change your mind here? I wasn't sure what you meant.

**Comment by maricn** [comment]
@lgandecki 
i guess the OP was complaining that the library precalculates the number of `maxTries` without taking into account the variable amount of time each `expectation()` execution might take..

that means the timeout to reject the `waitForExpect` might not turn out to be the one specified..
